backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "harga"
    label: "Harga Emas Hari Ini"
    files:
      - file: "data/harga.json"
        label: "Daftar Harga Antam Lengkap"
        name: "harga_antam"
        fields:
          - { label: "Antam 0.5 Gram (Rp)", name: "antam_05g", widget: "string" }
          - { label: "Antam 1 Gram (Rp)", name: "antam_1g", widget: "string" }
          - { label: "Antam 2 Gram (Rp)", name: "antam_2g", widget: "string" }
          - { label: "Antam 3 Gram (Rp)", name: "antam_3g", widget: "string" }
          - { label: "Antam 5 Gram (Rp)", name: "antam_5g", widget: "string" }
          - { label: "Antam 10 Gram (Rp)", name: "antam_10g", widget: "string" }
          - { label: "Antam 25 Gram (Rp)", name: "antam_25g", widget: "string" }
          - { label: "Antam 50 Gram (Rp)", name: "antam_50g", widget: "string" }
          - { label: "Antam 100 Gram (Rp)", name: "antam_100g", widget: "string" }
          - { label: "Antam 250 Gram (Rp)", name: "antam_250g", widget: "string" }
          - { label: "Antam 500 Gram (Rp)", name: "antam_500g", widget: "string" }
          - { label: "Antam 1000 Gram / 1 Kg (Rp)", name: "antam_1000g", widget: "string" }
